data:
  video_dir: ./data/videos
  feature_dir: ./data/features
  frame_count: 8
  image_size: 224
  test_split: 0.2
  val_split: 0.5
  low_variance_threshold: 1e-5
  class_map:
    real: 0
    deepfake: 1
    face2face: 2
    neuraltextures: 3
model:
  architecture: "xception"
  num_classes: 4
  dropout_rate: 0.3
  pretrained: true
  feature_dim: 2048
  classifier_hidden_size: 256
  flow_architecture: "resnet18"
  flow_feature_dim: 512
  use_flow: true
augmentation:
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1
  blur_sigma_min: 0.1
  blur_sigma_max: 2.0
  crop_scale_min: 0.8
  crop_scale_max: 1.0
face_detection:
  margin: 20
  min_face_size: 20
  thresholds: [0.6, 0.7, 0.7]
optical_flow:
  pyr_scale: 0.5
  levels: 3
  winsize: 15
  iterations: 3
  poly_n: 5
  poly_sigma: 1.2
  flags: 0
normalization:
  imagenet_mean: [0.485, 0.456, 0.406]
  imagenet_std: [0.229, 0.224, 0.225]
training:
  batch_size: 16
  device: "cuda"
  log_dir: logs
  checkpoint_dir: checkpoints
  epochs: 50
  learning_rate: 1e-4
  weight_decay: 1e-3
  scheduler_patience: 8
  scheduler_factor: 0.7
  early_stopping_patience: 15
  early_stopping_min_delta: 0.001
  class_weights: [1.0, 1.2, 1.2, 1.2]
  frames_std_threshold: 1.0